title: Sandi Scarangella
logo: docs/assets/S.Scarangella.JPG
description: Data Scientist
badges: docs/assets/microsoft-power-up-program-power-platform-course-co.png
remote_theme: pages-themes/minimal@v0.2.0
